In [1]:
import torch
import torch.nn as nn

# Sample input (batch of 6 data points, each with 8 features)
x = torch.tensor([[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0], 
                  [2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0], 
                  [3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0], 
                  [4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0],
                  [5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0],
                  [6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0]])

# Defining a simple network with BatchNorm1d for 8 features
class BatchNormNet(nn.Module):
    def __init__(self):
        super(BatchNormNet, self).__init__()
        self.batch_norm = nn.BatchNorm1d(num_features=8)  # Batch normalization over 8 features
    
    def forward(self, x):
        return self.batch_norm(x)

# Initialize the model
model = BatchNormNet()

# Forward pass through the model
output = model(x)

# Access the running mean and variance after the forward pass
running_mean = model.batch_norm.running_mean
running_var = model.batch_norm.running_var

print("Batch-Normalized Output:\n", output)
print("Running Mean (BatchNorm1d):\n", running_mean)
print("Running Variance (BatchNorm1d):\n", running_var)


Batch-Normalized Output:
 tensor([[-1.4638, -1.4638, -1.4638, -1.4638, -1.4638, -1.4638, -1.4638, -1.4638],
        [-0.8783, -0.8783, -0.8783, -0.8783, -0.8783, -0.8783, -0.8783, -0.8783],
        [-0.2928, -0.2928, -0.2928, -0.2928, -0.2928, -0.2928, -0.2928, -0.2928],
        [ 0.2928,  0.2928,  0.2928,  0.2928,  0.2928,  0.2928,  0.2928,  0.2928],
        [ 0.8783,  0.8783,  0.8783,  0.8783,  0.8783,  0.8783,  0.8783,  0.8783],
        [ 1.4638,  1.4638,  1.4638,  1.4638,  1.4638,  1.4638,  1.4638,  1.4638]],
       grad_fn=<NativeBatchNormBackward0>)
Running Mean (BatchNorm1d):
 tensor([0.3500, 0.4500, 0.5500, 0.6500, 0.7500, 0.8500, 0.9500, 1.0500])
Running Variance (BatchNorm1d):
 tensor([1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500])
