# Import Libraries

In [2]:
import torch

In [5]:
# define a variable with requires_grad
y = torch.rand(10)

x = torch.rand(10, requires_grad = True)
x

tensor([0.5099, 0.8483, 0.4939, 0.4681, 0.2442, 0.4255, 0.8565, 0.5799, 0.4488,
        0.8677], requires_grad=True)

In [8]:
b = (x**2).mean()
print(b)

b.backward()

tensor(0.3708, grad_fn=<MeanBackward0>)


In [10]:
print(x.grad)
print(2*x/10)

tensor([0.1020, 0.1697, 0.0988, 0.0936, 0.0488, 0.0851, 0.1713, 0.1160, 0.0898,
        0.1735])
tensor([0.1020, 0.1697, 0.0988, 0.0936, 0.0488, 0.0851, 0.1713, 0.1160, 0.0898,
        0.1735], grad_fn=<DivBackward0>)
