# Import

In [1]:
import torch
import torch.nn as nn

# Model

In [5]:
model = nn.Linear(10, 1)
weights = model.weight
print(f'{weights =}')
bias = model.bias
print(f'{bias =}')

weights =Parameter containing:
tensor([[-0.1193,  0.3047, -0.2694,  0.0484, -0.2612, -0.0467,  0.2989,  0.2416,
         -0.0067,  0.3027]], requires_grad=True)
bias =Parameter containing:
tensor([-0.0890], requires_grad=True)


# The Data

In [7]:
x = torch.zeros(10)
model(x)

tensor([-0.0890], grad_fn=<ViewBackward0>)