# import libraries

In [12]:
import torch

# examples

From a list

In [13]:
a = torch.tensor([1,2,3.0], dtype= torch.float32)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)

tensor([1., 2., 3.])
torch.Size([3])
1
torch.float32


Zeros

In [14]:
b = torch.rand([3, 1, 2], dtype = torch.float32)
print(  b)


tensor([[[0.9881, 0.3092]],

        [[0.6475, 0.6448]],

        [[0.7564, 0.2192]]])


In [15]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
m = torch.max(x, dim = - 1)
print(m)

torch.return_types.max(
values=tensor([3, 6, 9]),
indices=tensor([2, 2, 2]))


In [16]:
from PIL import Image
import numpy as np
img = Image.open('cat.jpg')
c = torch.as_tensor(np.array(img)).float()
print(c.shape)

torch.Size([360, 543, 3])


In [17]:
a = torch.arange(10)
b = torch.ones(10)
print(f'{a =}')
print(f'{b =}')
print(f'{a + b =}')

a =tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
b =tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
a + b =tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


In [42]:
randoms = torch.rand([2,5])
print(randoms)
idx = torch.max(randoms, dim = 1).indices
print(idx)
max_values = randoms[torch.arange(randoms.size(0)), idx]
print(max_values)

tensor([[0.6268, 0.5269, 0.3811, 0.2949, 0.8307],
        [0.2496, 0.6806, 0.6617, 0.8307, 0.7633]])
tensor([4, 3])
tensor([0.8307, 0.8307])
